// =============================================================
//  Contenido de las descripciones de puesto — Departamento de Redes
// =============================================================

#let fecha-edicion = "Agosto 2026"

#let coordinador = (
  clave: "coordinador",
  codigo: "TIC-RED-001",
  denominacion: "Scrum Master / Coordinador de Redes",
  subtitulo: "Coordinación y facilitación ágil del área de Redes",
  titular: "Oziel Rodman Ramos Torrez",
  categoria: "Directivo",
  departamento: "Tecnología · Redes",
  titulares: "1",
  jornada: "Mañana y tarde",
  fecha: fecha-edicion,
  finalidad: (
    [Dirigir y coordinar la operación integral de la infraestructura de red de la organización, garantizando disponibilidad, seguridad y rendimiento de los servicios de conectividad.],
    [Facilitar la aplicación del marco de trabajo Scrum dentro del equipo de Redes, removiendo impedimentos y asegurando la entrega continua de valor en cada iteración.],
    [Organizar al equipo de Redes —administración, seguridad y soporte— para el cumplimiento de los objetivos técnicos y de servicio comprometidos.],
    [Gestionar los recursos humanos, materiales y presupuestarios asignados al área de Redes.],
  ),
  areas: (
    [Disponibilidad y continuidad operativa de la red corporativa.],
    [Cumplimiento de los objetivos de cada sprint y de los acuerdos de nivel de servicio (SLA).],
    [Gestión de los recursos humanos y materiales del departamento.],
    [Ajuste de los resultados al presupuesto asignado al área.],
    [Madurez del equipo en la aplicación de metodologías ágiles.],
  ),
  funciones: (
    [Definir y supervisar el plan de trabajo, la arquitectura y las políticas de la red corporativa.],
    [Facilitar las ceremonias Scrum: planificación de sprint, reunión diaria, revisión y retrospectiva.],
    [Coordinar al equipo técnico —administrador de redes, especialista en seguridad y soporte— en sus objetivos específicos.],
    [Identificar y remover impedimentos que bloqueen el avance del equipo.],
    [Analizar reportes de disponibilidad, tráfico e incidentes y proponer soluciones técnicas o de mejora.],
    [Tomar decisiones ante imprevistos, contingencias o incidentes críticos dentro de su área.],
    [Representar al área de Redes ante la dirección y ante las demás jefaturas de Tecnología.],
  ),
  rel-jerarquicas: [Reporta a la Dirección de Tecnología y Producto.],
  rel-funcionales: [Dirige al Administrador de Redes, al Especialista en Seguridad de Redes y al responsable de Soporte y Monitoreo. Coordina con Infraestructura, Desarrollo y proveedores de servicios de telecomunicaciones.],
  responsabilidad: (
    [Supervisión directa del presupuesto y de los recursos tecnológicos asignados al área de Redes.],
    [Garantizar la seguridad y confidencialidad de la información que circula por la red.],
    [Toma de decisiones críticas que afectan la disponibilidad de los servicios de conectividad.],
    [Desarrollo profesional, evaluación y clima laboral del equipo a su cargo.],
  ),
  condiciones: (
    [Opera mayormente en entornos de oficina con posibilidad de trabajo remoto.],
    [Disponibilidad para atender emergencias fuera del horario laboral regular.],
    [Desplazamientos ocasionales a sedes o centros de datos para supervisión técnica.],
  ),
  riesgos: (
    [Estrés derivado de la necesidad de resolver incidencias críticas en tiempo reducido.],
    [Exposición a sobrecarga de trabajo en picos de demanda o durante ventanas de mantenimiento.],
    [Alta responsabilidad ante caídas de servicio que afectan a toda la organización.],
  ),
  requerimientos: (
    [Grado en Ingeniería en Sistemas, Informática, Telecomunicaciones o campos relacionados.],
    [Experiencia mínima de 5 años en gestión de equipos y de infraestructura de red.],
    [Certificación o formación acreditada en Scrum (PSM, CSM o equivalente).],
    [Conocimientos avanzados en redes LAN/WAN, enrutamiento, conmutación y gestión de sistemas.],
    [Habilidad para la toma de decisiones bajo presión y en entornos dinámicos.],
    [Manejo de herramientas de gestión ágil y de indicadores de servicio.],
  ),
  competencias: (
    [Liderazgo y gestión de equipos de alto desempeño.],
    [Orientación a resultados y resolución de problemas.],
    [Habilidades de comunicación, facilitación y negociación.],
    [Capacidad de análisis y mejora continua.],
    [Pensamiento estratégico aplicado a la infraestructura tecnológica.],
  ),
)

#let administrador = (
  clave: "administrador",
  codigo: "TIC-RED-002",
  denominacion: "Administrador de Redes",
  subtitulo: "Operación y administración de la infraestructura de red",
  titular: "Rodny Gerald Siles Barrenechea",
  categoria: "Profesional / Técnico especializado",
  departamento: "Tecnología · Redes",
  titulares: "1",
  jornada: "Mañana y tarde",
  fecha: fecha-edicion,
  finalidad: (
    [Diseñar, configurar y mantener la infraestructura de red —cableada e inalámbrica— que soporta los servicios de la organización.],
    [Garantizar la disponibilidad, el rendimiento y la escalabilidad de los enlaces, equipos de red y servicios asociados.],
    [Administrar el direccionamiento, la segmentación y las políticas de tráfico de la red corporativa.],
    [Optimizar el uso del ancho de banda y de los recursos de red asegurando eficiencia en costos.],
  ),
  areas: (
    [Disponibilidad y estabilidad de la infraestructura de red.],
    [Correcta segmentación lógica (VLAN) y direccionamiento IP.],
    [Optimización del rendimiento de enrutadores, conmutadores y puntos de acceso.],
    [Documentación técnica y diagramas de red actualizados.],
    [Automatización de tareas de configuración y respaldo de equipos.],
  ),
  funciones: (
    [Diseñar la topología de red y la arquitectura de conectividad (LAN, WAN, VLAN, VPN).],
    [Configurar y administrar enrutadores, conmutadores, cortafuegos y puntos de acceso inalámbrico.],
    [Administrar servicios de red: DHCP, DNS, NAT, calidad de servicio (QoS) y control de acceso.],
    [Ejecutar respaldos de configuración y aplicar actualizaciones de firmware de forma programada.],
    [Atender y escalar incidentes de conectividad de segundo nivel.],
    [Gestionar la relación técnica con proveedores de enlaces e Internet.],
    [Mantener actualizado el inventario de equipamiento de red y su documentación.],
  ),
  rel-jerarquicas: [Reporta al Scrum Master / Coordinador de Redes.],
  rel-funcionales: [Coordina con el Especialista en Seguridad de Redes en la aplicación de políticas y con Soporte y Monitoreo en la atención de incidentes. Colabora con Infraestructura y Desarrollo.],
  responsabilidad: (
    [Garantizar la operatividad continua de los equipos y enlaces de red.],
    [Custodia de las credenciales y configuraciones de los dispositivos de red.],
    [Administrar los recursos tecnológicos asignados: equipos, licencias y contratos de enlace.],
    [Aplicar los cambios de configuración conforme al procedimiento de gestión de cambios.],
  ),
  condiciones: (
    [Trabajo en entorno de oficina, centro de datos y administración remota de equipos.],
    [Participación en ventanas de mantenimiento programado, generalmente fuera del horario habitual.],
    [Uso prolongado de estaciones de trabajo y consolas de administración.],
  ),
  riesgos: (
    [Fatiga visual y postural por trabajo prolongado frente a pantallas.],
    [Estrés asociado a la resolución de caídas de enlace o fallas de equipamiento.],
    [Riesgo eléctrico y ergonómico durante intervenciones físicas en racks y gabinetes.],
  ),
  requerimientos: (
    [Ingeniería en Sistemas, Informática, Redes, Telecomunicaciones o carreras afines.],
    [Experiencia mínima de 3 años en administración de redes empresariales.],
    [Certificación en redes deseable (CCNA, JNCIA o equivalente).],
    [Dominio de enrutamiento y conmutación, VLAN, VPN, protocolos TCP/IP, OSPF y BGP.],
    [Conocimiento de sistemas operativos Linux y Windows Server.],
    [Manejo de herramientas de automatización y scripting (Python, Ansible o similares).],
  ),
  competencias: (
    [Pensamiento lógico y estructurado.],
    [Capacidad de análisis de sistemas complejos.],
    [Resolución de problemas técnicos bajo presión.],
    [Orden, disciplina documental y atención al detalle.],
    [Trabajo colaborativo con equipos técnicos.],
  ),
)

#let seguridad = (
  clave: "seguridad",
  codigo: "TIC-RED-003",
  denominacion: "Especialista en Seguridad de Redes",
  subtitulo: "Protección, hardening y respuesta ante incidentes",
  titular: "Luis Angel Paredes Torrez",
  categoria: "Profesional / Técnico especializado",
  departamento: "Tecnología · Redes",
  titulares: "1",
  jornada: "Mañana y tarde",
  fecha: fecha-edicion,
  finalidad: (
    [Proteger la integridad, disponibilidad y confidencialidad de la información que circula por la red corporativa.],
    [Definir, implementar y auditar las políticas de seguridad perimetral y de acceso a la red.],
    [Detectar, contener y responder ante incidentes de seguridad y actividad anómala.],
    [Asegurar el cumplimiento de las normativas y buenas prácticas de seguridad aplicables.],
  ),
  areas: (
    [Reducción de la superficie de exposición y de las vulnerabilidades detectadas.],
    [Efectividad de las reglas de cortafuegos y de los sistemas de detección de intrusiones.],
    [Tiempo de detección y de respuesta ante incidentes de seguridad.],
    [Cumplimiento de las políticas de seguridad y de los resultados de auditoría.],
    [Concienciación del personal en materia de seguridad de la información.],
  ),
  funciones: (
    [Diseñar y mantener las políticas de cortafuegos, listas de control de acceso y segmentación segura.],
    [Administrar sistemas de detección y prevención de intrusiones (IDS/IPS) y filtrado de contenido.],
    [Ejecutar análisis de vulnerabilidades y pruebas de penetración internas de forma periódica.],
    [Endurecer (hardening) la configuración de los dispositivos de red y de los servicios expuestos.],
    [Monitorear registros y eventos de seguridad; investigar y documentar incidentes.],
    [Coordinar la respuesta ante incidentes y elaborar el informe forense correspondiente.],
    [Capacitar al personal en buenas prácticas de seguridad y uso responsable de la red.],
  ),
  rel-jerarquicas: [Reporta al Scrum Master / Coordinador de Redes.],
  rel-funcionales: [Coordina con el Administrador de Redes la aplicación de controles y con Soporte y Monitoreo la detección temprana de eventos. Colabora con Infraestructura, Desarrollo y auditoría interna.],
  responsabilidad: (
    [Responsabilidad técnica sobre los controles de seguridad perimetral y de acceso.],
    [Manejo de información sensible, credenciales privilegiadas y evidencia de incidentes.],
    [Custodia y confidencialidad de los hallazgos de vulnerabilidades y auditorías.],
    [Decisiones de contención que pueden implicar la interrupción temporal de un servicio.],
  ),
  condiciones: (
    [Trabajo en entorno de oficina con administración remota de plataformas de seguridad.],
    [Disponibilidad para atención de incidentes críticos fuera del horario laboral.],
    [Exposición a jornadas extendidas durante investigaciones o auditorías.],
  ),
  riesgos: (
    [Estrés por la resolución de incidentes críticos con impacto reputacional.],
    [Alta responsabilidad operativa ante brechas de seguridad o fuga de información.],
    [Fatiga visual y sobrecarga cognitiva por el análisis continuo de registros y alertas.],
  ),
  requerimientos: (
    [Ingeniería en Sistemas, Informática, Redes o carreras afines.],
    [Experiencia mínima de 3 años en seguridad informática o seguridad de redes.],
    [Certificación deseable en seguridad (CCNA Security, CompTIA Security+, CEH o equivalente).],
    [Conocimiento de cortafuegos, IDS/IPS, VPN, PKI, cifrado y autenticación (RADIUS, 802.1X).],
    [Manejo de herramientas de análisis de tráfico y vulnerabilidades (Wireshark, Nmap, Nessus).],
    [Conocimiento de marcos de referencia como ISO 27001 y NIST.],
  ),
  competencias: (
    [Pensamiento analítico y criterio crítico.],
    [Rigurosidad, ética profesional y discreción.],
    [Capacidad de respuesta ante incidentes críticos.],
    [Actualización técnica permanente frente a nuevas amenazas.],
    [Comunicación clara de riesgos a públicos técnicos y no técnicos.],
  ),
)

#let soporte = (
  clave: "soporte",
  codigo: "TIC-RED-004",
  denominacion: "Soporte y Monitoreo de Redes",
  subtitulo: "Vigilancia continua y atención de incidentes de conectividad",
  titular: "Alvaro Ariel Torrez Calle",
  categoria: "Técnico / Operativo",
  departamento: "Tecnología · Redes",
  titulares: "1",
  jornada: "Mañana y tarde",
  fecha: fecha-edicion,
  finalidad: (
    [Vigilar de forma continua el estado, la disponibilidad y el rendimiento de la red y de sus servicios.],
    [Atender en primera línea los requerimientos e incidentes de conectividad de los usuarios internos.],
    [Detectar tempranamente degradaciones o fallas y escalarlas al nivel correspondiente.],
    [Mantener el registro documental de incidentes, cambios y métricas de servicio.],
  ),
  areas: (
    [Cobertura y vigencia del monitoreo sobre los activos de red.],
    [Tiempo de respuesta y de resolución en la atención de incidentes de primer nivel.],
    [Calidad y trazabilidad del registro de tickets e incidentes.],
    [Precisión de los reportes periódicos de disponibilidad y rendimiento.],
    [Satisfacción de los usuarios internos atendidos.],
  ),
  funciones: (
    [Operar las plataformas de monitoreo y configurar alertas, umbrales y tableros de control.],
    [Recibir, clasificar y atender los tickets de soporte relacionados con la red.],
    [Ejecutar diagnósticos de primer nivel y aplicar soluciones conocidas documentadas.],
    [Escalar al Administrador de Redes o al Especialista en Seguridad los casos que exceden su nivel.],
    [Elaborar reportes periódicos de disponibilidad, tráfico e incidentes.],
    [Verificar el estado físico de equipos, gabinetes y cableado; reportar anomalías.],
    [Mantener actualizada la base de conocimiento y los procedimientos operativos.],
  ),
  rel-jerarquicas: [Reporta al Scrum Master / Coordinador de Redes.],
  rel-funcionales: [Escala y coordina con el Administrador de Redes y con el Especialista en Seguridad de Redes. Atiende a los usuarios internos de todas las áreas de la organización.],
  responsabilidad: (
    [Vigilancia permanente del estado de la red y notificación oportuna de eventos.],
    [Registro fiel y completo de la información de incidentes y atenciones.],
    [Confidencialidad de los datos a los que accede durante las tareas de soporte.],
    [Cuidado del equipamiento e instrumental de diagnóstico asignado.],
  ),
  condiciones: (
    [Trabajo en oficina y en sala de monitoreo, con desplazamientos internos a puestos de usuario.],
    [Posibilidad de turnos o guardias para asegurar la cobertura del monitoreo.],
    [Uso continuo de pantallas de vigilancia y herramientas de diagnóstico.],
  ),
  riesgos: (
    [Fatiga visual y postural por vigilancia continua de tableros y pantallas.],
    [Estrés por atención simultánea de múltiples incidentes en horas pico.],
    [Riesgo ergonómico y eléctrico leve durante intervenciones físicas en puestos de trabajo.],
  ),
  requerimientos: (
    [Técnico superior o estudios universitarios en Sistemas, Informática, Redes o afines.],
    [Experiencia mínima de 1 a 2 años en soporte técnico o mesa de ayuda.],
    [Conocimiento de fundamentos de redes: TCP/IP, DNS, DHCP, cableado estructurado y Wi-Fi.],
    [Manejo de herramientas de monitoreo (Zabbix, PRTG, Nagios, Grafana o similares).],
    [Manejo de sistemas de tickets y documentación de procedimientos.],
    [Nociones de seguridad básica y de atención al usuario.],
  ),
  competencias: (
    [Atención al detalle y capacidad de observación sostenida.],
    [Orientación al servicio y trato cordial con el usuario.],
    [Comunicación clara y capacidad de reporte.],
    [Organización, método y seguimiento de procedimientos.],
    [Proactividad para la detección temprana de anomalías.],
  ),
)

#let todos = (coordinador, administrador, seguridad, soporte)
